/// Flutter icons DiceIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DiceIcon
///      fonts:
///       - asset: fonts/DiceIcon.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class DiceIcon {
  DiceIcon._();

  static const _kFontFam = 'DiceIcon';
  static const _kFontPkg = null;

  static const IconData dice_five = IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_four = IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_one = IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_six = IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_three = IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_two = IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData perspective_dice_one = IconData(0xea5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
